# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e62961298db1de2e9c6bae342ab60d221a5623b861a33561f7b78dae7d4a43eb2a3ce8fd5deb091957bac19f256a8e18fb2ebed2f999d6b7f0de84aec5704426

test:
  secret_key_base: 20ac972c60e587f552f94350bd0c14078a120080dd4c178de4ea5a4926ef776715dcf67da21716f24f07eb1e4824fe0e11bd4d00642fe70125225e5c34aad9eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
