# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)



Cinema.create (cinema: "Greenbelt 1 Cinemas")
Cinema.create (cinema: "Robinsons Magnolia")
Cinema.create (cinema: "Bonifacio High Street Cinema")
Cinema.create (cinema: "SM IMAX Theater")

Product.create(product: "La Grande Bellezza", cinema_id: Cinema.find_by(cinema:"Greenbelt 1 Cinemas").id)
Product.create(product: "Black Swan", cinema_id: Cinema.find_by(cinema:"Robinsons Magnolia").id)
Product.create(product: "The Broken", cinema_id: Cinema.find_by(cinema:"Bonifacio High Street Cinema").id)
Product.create(product: "Johnny English", cinema_id: Cinema.find_by(cinema:"SM IMAX Theater").id)

Theater.create(theater: "Theater 1", cinema_id: Cinema.find_by(cinema:"Greenbelt 1 Cinemas").id)
Theater.create(theater: "Theater 2", cinema_id: Cinema.find_by(cinema:"Greenbelt 1 Cinemas").id)
Theater.create(theater: "Theater 3", cinema_id: Cinema.find_by(cinema:"Robinsons Magnolia").id)
Theater.create(theater: "Theater 4", cinema_id: Cinema.find_by(cinema:"Robinsons Magnolia").id)
Theater.create(theater: "Theater 5", cinema_id: Cinema.find_by(cinema:"Bonifacio High Street Cinema").id)
Theater.create(product: "Theater 6", cinema_id: Cinema.find_by(cinema:"Bonifacio High Street Cinema").id)
Theater.create(product: "Theater 7", cinema_id: Cinema.find_by(cinema:"SM IMAX Theater").id)
Theater.create(product: "Theater 8", cinema_id: Cinema.find_by(cinema:"SM IMAX Theater").id)

Screening.create(screening: "10:00 Monday", theater_id: Theater.find_by(theater:"Theater 1").id)
Screening.create(screening: "12:00 Monday", theater_id: Theater.find_by(theater:"Theater 1").id)
Screening.create(screening: "14:00 Monday", theater_id: Theater.find_by(theater:"Theater 1").id)
Screening.create(screening: "16:00 Monday", theater_id: Theater.find_by(theater:"Theater 1").id)
Screening.create(screening: "10:00 Monday", theater_id: Theater.find_by(theater:"Theater 2").id)
Screening.create(screening: "12:00 Monday", theater_id: Theater.find_by(theater:"Theater 2").id)
Screening.create(screening: "14:00 Monday", theater_id: Theater.find_by(theater:"Theater 2").id)
Screening.create(screening: "16:00 Monday", theater_id: Theater.find_by(theater:"Theater 2").id)
Screening.create(screening: "10:00 Monday", theater_id: Theater.find_by(theater:"Theater 3").id)
Screening.create(screening: "12:00 Monday", theater_id: Theater.find_by(theater:"Theater 3").id)
Screening.create(screening: "14:00 Monday", theater_id: Theater.find_by(theater:"Theater 3").id)
Screening.create(screening: "16:00 Monday", theater_id: Theater.find_by(theater:"Theater 3").id)
Screening.create(screening: "10:00 Monday", theater_id: Theater.find_by(theater:"Theater 4").id)
Screening.create(screening: "12:00 Monday", theater_id: Theater.find_by(theater:"Theater 4").id)
Screening.create(screening: "14:00 Monday", theater_id: Theater.find_by(theater:"Theater 4").id)
Screening.create(screening: "16:00 Monday", theater_id: Theater.find_by(theater:"Theater 4").id)
Screening.create(screening: "10:00 Monday", theater_id: Theater.find_by(theater:"Theater 5").id)
Screening.create(screening: "12:00 Monday", theater_id: Theater.find_by(theater:"Theater 5").id)
Screening.create(screening: "14:00 Monday", theater_id: Theater.find_by(theater:"Theater 5").id)
Screening.create(screening: "16:00 Monday", theater_id: Theater.find_by(theater:"Theater 5").id)
Screening.create(screening: "10:00 Monday", theater_id: Theater.find_by(theater:"Theater 6").id)
Screening.create(screening: "12:00 Monday", theater_id: Theater.find_by(theater:"Theater 6").id)
Screening.create(screening: "14:00 Monday", theater_id: Theater.find_by(theater:"Theater 6").id)
Screening.create(screening: "16:00 Monday", theater_id: Theater.find_by(theater:"Theater 6").id)
Screening.create(screening: "10:00 Monday", theater_id: Theater.find_by(theater:"Theater 7").id)
Screening.create(screening: "12:00 Monday", theater_id: Theater.find_by(theater:"Theater 7").id)
Screening.create(screening: "14:00 Monday", theater_id: Theater.find_by(theater:"Theater 7").id)
Screening.create(screening: "16:00 Monday", theater_id: Theater.find_by(theater:"Theater 7").id)
Screening.create(screening: "10:00 Monday", theater_id: Theater.find_by(theater:"Theater 8").id)
Screening.create(screening: "12:00 Monday", theater_id: Theater.find_by(theater:"Theater 8").id)
Screening.create(screening: "14:00 Monday", theater_id: Theater.find_by(theater:"Theater 8").id)
Screening.create(screening: "16:00 Monday", theater_id: Theater.find_by(theater:"Theater 8").id)